### ISSUE TITLE
Bug compiling the library (yacc command not found)

### ISSUE THREAD

**Issue by magnese** [ugfem/ug#8]
Hi, 
I cloned the repository and I tried compile it

autoconf -is
./configure --enable-parallel --enable-dune
make

but I obtained the following error

libtool: link: ar cru .libs/libdomS3.a  libdomS3_la-std_domain.o libdomS3_la-std_parallel.o libdomS3_la-domains3d.o
libtool: link: ranlib .libs/libdomS3.a
libtool: link: ( cd ".libs" && rm -f "libdomS3.la" && ln -s "../libdomS3.la" "libdomS3.la" )
make[3]: Leaving directory `/usr/local_machine/ug/dom/std'
Making all in lgm
make[3]: Entering directory`/usr/local_machine/ug/dom/lgm'
Making all in ngin
make[4]: Entering directory `/usr/local_machine/ug/dom/lgm/ngin'
test -f ngin-yacc.cc || /bin/bash ../../../ylwrap ngin-yacc.yy y.tab.c ngin-yacc.cc y.tab.h`echo ngin-yacc.cc | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/`y.output ngin-yacc.output -- yacc -d -p ng 
../../../ylwrap: line 176: yacc: command not found
make[4]: *** [ngin-yacc.cc] Error 127
make[4]: Leaving directory`/usr/local_machine/ug/dom/lgm/ngin'
make[3]: **\* [all-recursive] Error 1
make[3]: Leaving directory `/usr/local_machine/ug/dom/lgm'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory`/usr/local_machine/ug/dom'
make[1]: **\* [all-recursive] Error 1
make[1]: Leaving directory `/usr/local_machine/ug'
make: **\* [all] Error 2

I cannot attach the config.log file but if you need it I can copy and paste here. 
For what concern yacc I found this line in the config.log:

configure:4872: checking for byacc
configure:4902: result: no

ac_cv_env_YACC_set=
ac_cv_env_YACC_value=

YACC='yacc'

Thank you,
cheers,
Marco

**Comment by epipping** [comment]
This isn't really a bug, is it? yacc (in the form of e.g. GNU bison) is a dependency. Granted, maybe configure should fail earlier...

**Comment by magnese** [comment]
Is byacc the package needed in Ubuntu?

**Comment by epipping** [comment]
byacc is one provider, yes. bison would be another.

**Comment by magnese** [comment]
Thanks. 

By the way I have seen that ug should me moved directly into dune-grid therefore I think this will simplify a lot the compilation/usage of ug within dune.
